# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs: 
  slack: circleci/slack@4.12.5
  aws-s3: circleci/aws-s3@3.1.1
executors:
  scratchjr-website-executor:
    docker:
      - image: cimg/node:17.0.0
    resource_class: small
jobs:
  setup_app:
    executor: scratchjr-website-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm  install
      - run:
          name: List
          command: ls -la
workflows:
  build_and_deploy_scratchjr-website:
    jobs: 
      - setup_app:
          name: Setup App
